### ISSUE TITLE
Nevýrazné odkazy v textu

### ISSUE THREAD

**Issue by Markaos** [jelinekp/zapisy#12]
Možná bychom je mohli alespoň nějak zvýraznit...

**Comment by jelinekp** [comment]
já myslím, že ty odkazy nejsou podstatné a na mém monitoru to vypadá rozlišeně...

**Comment by Markaos** [comment]
Odkaz na Dokumenty Google je důležitý (když už tam je, tak ať je vidět a není to jako kouzelné `SECONDARY_SELECTION`, o kterém cca 90% uživatelů neví)

**Comment by jelinekp** [comment]
okok, ale mě se podtržení nelíbí...

**Comment by Markaos** [comment]
Tak barva, to je jedno. Jde mi o to, že třeba na mobilu bych si těch odkazů ani nevšiml, kdybych o nich nevěděl

**Comment by jelinekp** [comment]
mě je to vlastně jedno... zkus si s tím nějak pohrát (s barvou)

**Comment by jelinekp** [comment]
navrhuji je nějak zvýraznit (třeba i podtržítkem) jenom v mobilní verzi, (v desktop stačí možná víc světlá barva)...
