### ISSUE TITLE
mobily s full hd a vyšším rozlišením

### ISSUE THREAD

**Issue by jelinekp** [jelinekp/zapisy#13]
chtělo by to nějak detekovat high dpi...

**Comment by Markaos** [comment]
Proč? px je v CSS nezávislý na dpi

**Comment by jelinekp** [comment]
ne já myslel, že media atribut dokáže zjišťovat i podle dpi...
po detekci high dpi by se použil mobile.css (u media atributu lze použít or)

**Comment by Markaos** [comment]
Pokud jsem to správně pochopil, tak pokud máš 730px širokou obrazovku, tak máš prostě k dispozici 730px (a všechny velikosti na té stránce jsou zapsané v pixelech, takže kdyby to tak nebylo, tak hodně štěstí při čtení mikrotextu - i text máme řešený pomocí pixelů)

**Comment by jelinekp** [comment]
na high dpi by mohlo být zvlášť css...

**Comment by Markaos** [comment]
Ne, myslel jsem to tak, že CSS jasně říká, že px není závislé na rozlišení a zobrazí se všude +/- stejně (pokud stavíš prohlížeč pro HiDPI, tak musíš vyřešit přepočítávání na skutečné pixely, ale to má řešit autor prohlížeče, ne autor webu - nic jako HiDPI web neexistuje (doufám :)))

**Comment by jelinekp** [comment]
okok, snad to bude na kryštofovém ajfounu dobře fungovat :)

**Comment by jelinekp** [comment]
takže zavírám

**Comment by Markaos** [comment]
Teda, od určitého rozlišení (prostě když máš HiDPI, tak se to v prohlížeči přepočítává na skutečné pixely a ty to nemusíš řešit)

**Comment by Markaos** [comment]
A dodatečně můžu potvrdit, že na FullHD mobilu s tím nejsou žádné problémy ;)
