### ISSUE TITLE
co takhle nějakou ikonu?

### ISSUE THREAD

**Issue by jelinekp** [jelinekp/zapisy#16]

**Comment by Markaos** [comment]
Nahrál jsem WIP verzi ikon (je 1:35, už jdu spát). Němčina, biologie a dějepis budou potřebovat pár úprav, chemie a občanská výchova ~ ujde.

**Comment by jelinekp** [comment]
Tys ty ikony vzal takhle doslova? Já myslel jenom ikonu v kartě webu... Ale ty ikony předmětů jsou dobré...

**Comment by jelinekp** [comment]
ok, jdu s tím na server

**Comment by jelinekp** [comment]
ta moje ikona je na desktopu odporná, ale na mobilu ujde [](http://zapisy.kvalitne.cz/ikonavmobilu.png)

**Comment by Markaos** [comment]
Tak zrovna na mobilu ji nevidím :) (vestavěný prohlížeč favicon nezobrazuje)

**Comment by jelinekp** [comment]
zavírám
