### ISSUE TITLE
SVG ikony předmětů

### ISSUE THREAD

**Issue by Markaos** [jelinekp/zapisy#18]
Mobily zobrazují ikony ve vyšším rozlišení než by měly, takže na nich mé ikony vypadají ještě hůř než na desktopu. Při použití SVG obrázků se bude vždy kreslit v ideálním rozlišení (i pro HiDPI monitory)

**Comment by jelinekp** [comment]
tzn. vektorová grafiak?

**Comment by Markaos** [comment]
Přesně. S podporou by neměl být problém, SVG ikony se používají i na Rootu ( :) )

**Comment by jelinekp** [comment]
ta nová ikona: je o mnoho lepší... :+1:

**Comment by Markaos** [comment]
Občanská výchova se tolik nepovedla, ale furt lepší než mít napevno 32x32 px
