### ISSUE TITLE
Podpora apple-touch-icon

### ISSUE THREAD

**Issue by Markaos** [jelinekp/zapisy#19]
Ať má Kryštof radost... :smile:
iOS při přidání záložky na plochu hledá ikonu apple-touch-icon (nejlépe ve svém rozlišení, ale stačí 72x72 px). Pokud budeme přidávat ikonu pro Chrome, tak tohle už by neměl být problém.

**Comment by jelinekp** [comment]
ta ikona je 128x128

**Comment by Markaos** [comment]
Ta ikona hlavně nemá být ICO, ale PNG... (a samozřejmě nemá být větší než všechny ostatní obrázky dohromady)
