### ISSUE TITLE
Alternativní favicon pro Google Chrome na Androidu

### ISSUE THREAD

**Issue by Markaos** [jelinekp/zapisy#20]
Google Chrome se při přidávání záložky na plochu snaží najít favicon s rozlišením 512x512 px. Můžeme ho vytvořit. Vyřešením tohoto problému vyřešíme i #19

**Comment by jelinekp** [comment]
není 512 x 512 moc? (já myslím že 128 na 128 stačí - ale hdpi -> uděláme 512 x 512) (kdyžtak stačí vyškálovat stávající ikonu)

**Comment by Markaos** [comment]
Právě 512x512 je dost místa na něco normálního (+ to nemá být ICO, ale PNG)

**Comment by jelinekp** [comment]
aha, tak to udělej...
