### ISSUE TITLE
Animované ikony

### ISSUE THREAD

**Issue by Markaos** [jelinekp/zapisy#22]
Mohlo by být zajímavé, kdyby se ikony po najetí myši změnily na animované. Podpora v prohlížečích je celkem dobrá ([Can I Use.com](http://caniuse.com/svg-smil), problémy má jenom IE a Edge)

**Comment by Markaos** [comment]
Ukázka s animovanou fyzikou je ve větvi `animations`

**Comment by jelinekp** [comment]
to je mrtě... klidně v tom pokračuj

**Comment by Markaos** [comment]
Animace v tuto chvíli nejsou podporované
