### ISSUE TITLE
Přidat písemky/testy

### ISSUE THREAD

**Issue by Markaos** [jelinekp/zapisy#25]
Možnost zapsat písemku na Bakaláře nějak chybí (a stejně by ji učitelé nevyužívali). Taková funkce by se na zápisech hodila

**Comment by jelinekp** [comment]
Jojo, můžeš to udělat ;)
Btw, v mobilu se issues dělají přes email výborné

Dne 30. 7. 2016 22:06 napsal uživatel "Markaos" notifications@github.com:

**Comment by Markaos** [comment]
Zbývá už jenom user-friendly rozhraní

**Comment by jelinekp** [comment]
ano, rozhraní pro správu... design bohužel musíš vymyslet sám ;)

**Comment by Markaos** [comment]
Rozhraní už je kompletní, jenom musí být hezčí
