### ISSUE TITLE
Rozdělit položky zápisů do skupin

### ISSUE THREAD

**Issue by jelinekp** [jelinekp/zapisy#36]
Na hlavní stránce - pro snadnější orientaci.
Př.
Přírodní vědy
Jazyky
Český jazyk a literatura
Ostatní

**Comment by jelinekp** [comment]
Třeba takhle, co na to říkáš? Snad se ten obrázek načte :D
![reorganizace zápisů](http://jelinekp.wz.cz/zapisy/reorganizace-zapisu-github-issue.jpg)
Kdyby ne, tak: http://jelinekp.wz.cz/zapisy/reorganizace-zapisu-github-issue.jpg

**Comment by jelinekp** [comment]
Problém je, že nevím jak to provést - musel bych se hrabat v tom PHP. Přidělil bych ve workbooks.json atributy skupin a potom je podle toho zařadil do indexu (ale musí to být konzistentní i v mobilní verzi) potažmo později třeba i do mobile app.

**Comment by Markaos** [comment]
PHP část nemá rozdíl mezi mobilní a desktop verzí - celé je to řešené pomocí CSS

**Comment by Markaos** [comment]
Dokumentace: dělení je aktuálně řešené ve workbooks-grouped.json, původní workbooks.json je používaný mobilní aplikací a "klasickým" zobrazením Zápisů
