### ISSUE TITLE
Přidat do kontributorů Roberta

### ISSUE THREAD

**Issue by jelinekp** [jelinekp/zapisy#40]
Robert nám prý zaplatí, když bude VIP zmíněn na hlavní stránce ;)

**Comment by Markaos** [comment]
Tak se nauč pracovat s partfiles - footer je statická část, to dáš

**Comment by jelinekp** [comment]
Nevím už kdy to bylo, ale vyřešeno ;)
Aha: 92515a43105ed037d9ff519cad6da1001eee9dd1
