### ISSUE TITLE
jiná barva pozadí a odkazů???

### ISSUE THREAD

**Issue by jelinekp** [jelinekp/zapisy#8]
místo té světlemodré & místo: darkblue;

**Comment by jelinekp** [comment]
klidně bych tam dal zelenou a ty odkazy do černé...

**Comment by Markaos** [comment]
V mobilní verzi už ty odkazy černé jsou, podívej se na větev `mobile_version`. Pozadí podle mě celkem jde

**Comment by jelinekp** [comment]
okok, zavírám
