### ISSUE TITLE
Sloučení mobilní a desktopové verze

### ISSUE THREAD

**Issue by Markaos** [jelinekp/zapisy#9]
Nahrál jsem mobilní verzi do větve `mobile_version`, teď je čas ji spojit s větví `master`. Asi nejvýraznější změna je odstranění samostatné buňky pro archiv

**Comment by Markaos** [comment]
Co se mě týče, můžeme `master` nahradit mobilní verzí

**Comment by jelinekp** [comment]
provedeno
